# Generated by Django 2.2.3 on 2021-01-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_roles',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Accountant'), (3, 'Store'), (4, 'Worker')], default=4),
        ),
    ]
