# Generated by Django 2.2.3 on 2021-05-24 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210115_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='User_District', to='accounts.District'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='User_Region', to='accounts.Region'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_roles',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Accountant'), (3, 'Store'), (4, 'Surveyor')], default=4),
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Ward')),
            ],
        ),
    ]
