# Generated by Django 2.2.3 on 2021-01-15 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('unit_of_size', models.CharField(max_length=20)),
                ('material', models.CharField(blank=True, max_length=20, null=True)),
                ('Manufacturer', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/equipments/')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyProject',
            fields=[
                ('proid', models.AutoField(primary_key=True, serialize=False)),
                ('site_No', models.IntegerField(null=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WellInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact1', models.CharField(blank=True, max_length=20)),
                ('contact2', models.CharField(blank=True, max_length=20, null=True)),
                ('depth', models.IntegerField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='photo/well/')),
                ('Video', models.FileField(blank=True, null=True, upload_to='video/well/')),
                ('equipment', models.ManyToManyField(blank=True, related_name='requirement', to='survey_project.Equipment')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='WellSite_Info', to='survey_project.SurveyProject')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Stored_items', to='survey_project.Equipment')),
                ('uploader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Uploaded_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(blank=True, max_length=55)),
                ('Current_source', models.CharField(blank=True, max_length=100)),
                ('Distance_source', models.CharField(blank=True, max_length=20)),
                ('Affected_people', models.IntegerField(blank=True)),
                ('Picture', models.ImageField(blank=True, null=True, upload_to='photo/currSource/')),
                ('Video', models.FileField(blank=True, null=True, upload_to='video/currSource/')),
                ('Attachment', models.FileField(blank=True, null=True, upload_to='attachments/currSource/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Source_District', to='accounts.District')),
                ('Region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Source_Region', to='accounts.Region')),
                ('Ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Source_Ward', to='accounts.Ward')),
                ('site_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Site_Info', to='survey_project.SurveyProject')),
            ],
        ),
    ]
