# Generated by Django 2.2.3 on 2021-06-08 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20210608_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('unit_of_size', models.CharField(blank=True, choices=[('Km', 'Kilometre'), ('Hm', 'Hectometre'), ('Dcm', 'Decametre'), ('M', 'Metre'), ('Dc', 'Decimetre'), ('Cm', 'Centimetre'), ('Mm', 'Millimetre')], default='Km', max_length=4, null=True)),
                ('material', models.CharField(blank=True, max_length=20, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/equipments/')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyProject',
            fields=[
                ('proid', models.AutoField(primary_key=True, serialize=False)),
                ('site_No', models.IntegerField()),
                ('Ward', models.CharField(blank=True, max_length=55, null=True)),
                ('Location', models.CharField(blank=True, max_length=55, null=True)),
                ('Current_source', models.CharField(blank=True, max_length=100, null=True)),
                ('Distance_source', models.CharField(blank=True, max_length=20, null=True)),
                ('Affected_people', models.IntegerField(blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('District', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Source_District', to='accounts.District')),
                ('Region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Source_Region', to='accounts.Region')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WellInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact1', models.CharField(blank=True, max_length=20)),
                ('contact2', models.CharField(blank=True, max_length=20, null=True)),
                ('depth', models.IntegerField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='photo/well/')),
                ('Video', models.FileField(blank=True, null=True, upload_to='video/well/')),
                ('equipment', models.ManyToManyField(blank=True, related_name='requirement', to='survey_project.Equipment')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='WellSite_Info', to='survey_project.SurveyProject')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/currSource/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_project.SurveyProject', verbose_name='SurveywithVideo')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('buy_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Stored_items', to='survey_project.Equipment')),
                ('uploader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Uploaded_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='photo/currSource/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_project.SurveyProject', verbose_name='SurveywithPhoto')),
            ],
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/currSource/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_project.SurveyProject', verbose_name='SurveywithAttachment')),
            ],
        ),
    ]
