# Generated by Django 2.2.3 on 2021-05-24 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_project', '0001_initial'),
    ]

    operations = [
    ]
