# Generated by Django 2.2.3 on 2021-01-18 16:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210115_1708'),
        ('survey_project', '0002_store_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='Manufacturer',
            new_name='manufacturer',
        ),
        migrations.AddField(
            model_name='equipment',
            name='size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyproject',
            name='Affected_people',
            field=models.IntegerField(blank=True, default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyproject',
            name='Attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/currSource/'),
        ),
        migrations.AddField(
            model_name='surveyproject',
            name='Current_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='surveyproject',
            name='Distance_source',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='surveyproject',
            name='District',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Source_District', to='accounts.District'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyproject',
            name='Location',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='surveyproject',
            name='Picture',
            field=models.ImageField(blank=True, null=True, upload_to='photo/currSource/'),
        ),
        migrations.AddField(
            model_name='surveyproject',
            name='Region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Source_Region', to='accounts.Region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyproject',
            name='Video',
            field=models.FileField(blank=True, null=True, upload_to='video/currSource/'),
        ),
        migrations.AddField(
            model_name='surveyproject',
            name='Ward',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Source_Ward', to='accounts.Ward'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyproject',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='CurrentSource',
        ),
    ]
