# Generated by Django 2.2.3 on 2021-05-24 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_project', '0003_auto_20210118_1923'),
        ('survey_project', '0002_auto_20210524_1404'),
    ]

    operations = [
    ]
