# Generated by Django 2.2.3 on 2021-05-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_project', '0004_merge_20210524_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='unit_of_size',
            field=models.CharField(choices=[('Km', 'Kilometre'), ('Hm', 'Hectometre'), ('Dcm', 'Decametre'), ('M', 'Metre'), ('Dc', 'Decimetre'), ('Cm', 'Centimetre'), ('Mm', 'Millimetre')], default='Km', max_length=4),
        ),
        migrations.AlterField(
            model_name='store',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveyproject',
            name='site_No',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
